### ISSUE TITLE
All build tests failing

### ISSUE THREAD

**Issue by iFreilicht** [jackhumbert/qmk_firmware#653] opened 2016-08-18 10:45 UTC
Currently all build tests from Travis CI are failing on the planck circuit layout. [Example here](https://travis-ci.org/jackhumbert/qmk_firmware/builds/153217928).

```
Compiling planck/planck with circuit                                                                   [ERRORS]
../../keyboards/planck/keymaps/circuit/keymap.c:46:29: error: conflicting types for ‘tap_dance_actions’
 const qk_tap_dance_action_t tap_dance_actions[] = {
                             ^
In file included from ../../quantum/quantum.h:60:0,
                 from ../../keyboards/planck/planck.h:11,
                 from ../../keyboards/planck/keymaps/circuit/keymap.c:3:
../../quantum/process_keycode/process_tap_dance.h:53:30: note: previous declaration of ‘tap_dance_actions’ was here
 extern qk_tap_dance_action_t tap_dance_actions[];
                              ^
 | 
 | 
 | 
make[1]: *** [../../.build/obj_planck_rev4_circuit/keyboards/planck/keymaps/circuit/keymap.o] Error 1
make: *** [/keyboards/planck-all] Error 1
```

This should be fixed asap.

**Comment by algernon** [comment] 2016-08-18 11:04
I'll prep a PR to fix this in a bit. The problem is that a tap-dance API break was merged before a keymap that used the old API... and travis does not rerun tests, so this was not discovered early...

Anyway, PR incoming, it's a trivial fix: remove `const` from the beginning of the line it complains about.

**Closed** 2016-08-18 14:04 UTC
